db.movies.find(
    {$or:[
        {category:{
            $all:["sci-fi"]
        }},
        {ratings:{
            $elemMatch:{$gte:199}
        }}
    ]},
    {_id:false,title:true,ratings:true,category:true}
)